### ISSUE TITLE
next - Mercure

### ISSUE THREAD

**Issue by Seboran** [Seboran/generateur-musique#11]
- [x] Correction de l'algorithme de propagation #8
- [x] Export de midi 🕛 généré #9 
- [ ] (bonus) Ajout de règles sudoku custom #10 
- [x] Régler l’ordre des notes 🎶 
- [ ] Rendre plus joli l’affichage des notes 🎶 
- [x] Ajouter un bouton retour ⏪ 
- [x] Joli design
- [ ] Améliorer la saisie des notes
